export default [{
	"hangYeFenLeiDaiMa": "J",
	"hangYeFenLeiName": "金融业",
	"children": [{
		"hangYeFenLeiDaiMa": "J66",
		"hangYeFenLeiName": "货币金融服务",
    "pid": 'J',
		"children": [
			{
				"hangYeFenLeiDaiMa": "J661",
				"hangYeFenLeiName": "货币金融服务1",
				"pid": 'J66'
			},
			{
				"hangYeFenLeiDaiMa": "J662",
				"hangYeFenLeiName": "货币金融服务2",
				"pid": 'J66'
			},
			{
				"hangYeFenLeiDaiMa": "J663",
				"hangYeFenLeiName": "货币金融服务3",
				"pid": 'J66'
			},
			{
				"hangYeFenLeiDaiMa": "J664",
				"hangYeFenLeiName": "货币金融服务4",
				"pid": 'J66'
			}
		]
	}, {
		"hangYeFenLeiDaiMa": "J67",
		"hangYeFenLeiName": "资本市场服务",
    "pid": 'J',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "J68",
		"hangYeFenLeiName": "保险业",
    "pid": 'J',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "J69",
		"hangYeFenLeiName": "其他金融业",
    "pid": 'J',
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "M",
	"hangYeFenLeiName": "科学研究和技术服务业",
	"children": [{
		"hangYeFenLeiDaiMa": "M73",
		"hangYeFenLeiName": "研究和试验发展",
    "pid": 'M',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "M74",
		"hangYeFenLeiName": "专业技术服务业",
    "pid": 'M',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "M75",
		"hangYeFenLeiName": "科技推广和应用服务业",
    "pid": 'M',
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "R",
	"hangYeFenLeiName": "文化、体育和娱乐业",
	"children": [{
		"hangYeFenLeiDaiMa": "R85",
		"hangYeFenLeiName": "新闻和出版业",
    "pid": 'R',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "R86",
		"hangYeFenLeiName": "广播、电视、电影和影视录音制作业",
    "pid": 'R',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "R87",
		"hangYeFenLeiName": "文化艺术业",
    "pid": 'R',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "R88",
		"hangYeFenLeiName": "体育",
    "pid": 'R',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "R89",
		"hangYeFenLeiName": "娱乐业",
    "pid": 'R',
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "F",
	"hangYeFenLeiName": "批发和零售业",
	"children": [{
		"hangYeFenLeiDaiMa": "F51",
		"hangYeFenLeiName": "批发业",
    "pid": 'F',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "F52",
		"hangYeFenLeiName": "零售业",
    "pid": 'F',
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "N",
	"hangYeFenLeiName": "水利、环境和公共设施管理业",
	"children": [{
		"hangYeFenLeiDaiMa": "N76",
		"hangYeFenLeiName": "水利管理业",
    "pid": 'N',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "N77",
		"hangYeFenLeiName": "生态保护和环境治理业",
    "pid": 'N',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "N78",
		"hangYeFenLeiName": "公共设施管理业",
    "pid": 'N',
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "E",
	"hangYeFenLeiName": "建筑业",
	"children": [{
		"hangYeFenLeiDaiMa": "E47",
    "pid": 'E',
		"hangYeFenLeiName": "房屋建筑业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "E48",
		"hangYeFenLeiName": "土木工程建筑业",
    "pid": 'E',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "E49",
    "pid": 'E',
		"hangYeFenLeiName": "建筑安装业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "E50",
    "pid": 'E',
		"hangYeFenLeiName": "建筑装饰和其他建筑业",
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "C",
	"hangYeFenLeiName": "制造业",
	"children": [{
		"hangYeFenLeiDaiMa": "C13",
    "pid": 'C',
		"hangYeFenLeiName": "农副食品加工业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C14",
    "pid": 'C',
		"hangYeFenLeiName": "食品制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C15",
    "pid": 'C',
		"hangYeFenLeiName": "酒、饮料和精制茶制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C16",
    "pid": 'C',
		"hangYeFenLeiName": "烟草制品业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C17",
    "pid": 'C',
		"hangYeFenLeiName": "纺织业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C18",
    "pid": 'C',
		"hangYeFenLeiName": "纺织服装、服饰业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C19",
		"hangYeFenLeiName": "皮革、毛皮、羽毛及其制品和制鞋业",
    "pid": 'C',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C20",
    "pid": 'C',
		"hangYeFenLeiName": "木材加工和木、竹、藤、棕、草制品业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C21",
    "pid": 'C',
		"hangYeFenLeiName": "家具制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C22",
    "pid": 'C',
		"hangYeFenLeiName": "造纸和纸制品业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C23",
		"hangYeFenLeiName": "印刷和记录媒介复制业",
    "pid": 'C',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C24",
    "pid": 'C',
		"hangYeFenLeiName": "文教、工美、体育和娱乐用品制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C25",
    "pid": 'C',
		"hangYeFenLeiName": "石油加工、炼焦和核燃料加工业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C26",
    "pid": 'C',
		"hangYeFenLeiName": "化学原料和化学制品制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C27",
    "pid": 'C',
		"hangYeFenLeiName": "医药制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C28",
    "pid": 'C',
		"hangYeFenLeiName": "化学纤维制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C29",
    "pid": 'C',
		"hangYeFenLeiName": "橡胶和塑料制品业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C30",
    "pid": 'C',
		"hangYeFenLeiName": "非金属矿物制品业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C31",
    "pid": 'C',
		"hangYeFenLeiName": "黑色金属冶炼和压延加工业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C32",
    "pid": 'C',
		"hangYeFenLeiName": "有色金属冶炼和压延加工业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C33",
    "pid": 'C',
		"hangYeFenLeiName": "金属制品业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C34",
    "pid": 'C',
		"hangYeFenLeiName": "通用设备制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C35",
    "pid": 'C',
		"hangYeFenLeiName": "专用设备制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C36",
    "pid": 'C',
		"hangYeFenLeiName": "汽车制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C37",
    "pid": 'C',
		"hangYeFenLeiName": "铁路、船舶、航空航天和其他运输设备制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C38",
    "pid": 'C',
		"hangYeFenLeiName": "电气机械和器材制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C39",
    "pid": 'C',
		"hangYeFenLeiName": "计算机、通信和其他电子设备制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C40",
    "pid": 'C',
		"hangYeFenLeiName": "仪器仪表制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C41",
    "pid": 'C',
		"hangYeFenLeiName": "其他制造业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C42",
    "pid": 'C',
		"hangYeFenLeiName": "废弃资源综合利用业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "C43",
    "pid": 'C',
		"hangYeFenLeiName": "金属制品、机械和设备修理业",
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "B",
	"hangYeFenLeiName": "采矿业",
	"children": [{
		"hangYeFenLeiDaiMa": "B06",
    "pid": 'B',
		"hangYeFenLeiName": "煤炭开采和洗选业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "B07",
    "pid": 'B',
		"hangYeFenLeiName": "石油和天然气开采业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "B08",
    "pid": 'B',
		"hangYeFenLeiName": "黑色金属矿采选业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "B09",
    "pid": 'B',
		"hangYeFenLeiName": "有色金属矿采选业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "B10",
    "pid": 'B',
		"hangYeFenLeiName": "非金属矿采选业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "B11",
    "pid": 'B',
		"hangYeFenLeiName": "开采辅助活动",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "B12",
    "pid": 'B',
		"hangYeFenLeiName": "其他采矿业",
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "O",
	"hangYeFenLeiName": "居民服务、修理和其他服务业",
	"children": [{
		"hangYeFenLeiDaiMa": "O79",
		"hangYeFenLeiName": "居民服务业",
    "pid": '0',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "O80",
    "pid": '0',
		"hangYeFenLeiName": "机动车、电子产品和日用产品修理业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "O81",
    "pid": '0',
		"hangYeFenLeiName": "其他服务业",
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "H",
	"hangYeFenLeiName": "住宿和餐饮业",
	"children": [{
		"hangYeFenLeiDaiMa": "H61",
    "pid": 'H',
		"hangYeFenLeiName": "住宿业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "H62",
    "pid": 'H',
		"hangYeFenLeiName": "餐饮业",
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "L",
	"hangYeFenLeiName": "租赁和商务服务业",
	"children": [{
		"hangYeFenLeiDaiMa": "L71",
    "pid": 'L',
		"hangYeFenLeiName": "租赁业",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "L72",
		"hangYeFenLeiName": "商务服务业",
    "pid": 'L',
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "I",
	"hangYeFenLeiName": "信息传输、软件和信息技术服务业",
	"children": [{
		"hangYeFenLeiDaiMa": "I63",
    "pid": 'I',
		"hangYeFenLeiName": "电信、广播电视和卫星传输服务",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "I64",
		"hangYeFenLeiName": "互联网和相关服务",
    "pid": 'I',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "I65",
    "pid": 'I',
		"hangYeFenLeiName": "软件和信息技术服务业",
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "S",
	"hangYeFenLeiName": "公共管理、社会保障和社会组织",
	"children": [{
		"hangYeFenLeiDaiMa": "S90",
    "pid": 'S',
		"hangYeFenLeiName": "中国共产党机关",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "S91",
    "pid": 'S',
		"hangYeFenLeiName": "国家机构",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "S92",
    "pid": 'S',
		"hangYeFenLeiName": "人民政协、民主党派",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "S93",
    "pid": 'S',
		"hangYeFenLeiName": "社会保障",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "S94",
    "pid": 'S',
		"hangYeFenLeiName": "群众团体、社会团体和其他成员组织",
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "S95",
    "pid": 'S',
		"hangYeFenLeiName": "基层群众自治组织",
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "A",
	"hangYeFenLeiName": "农、林、牧、渔业",
	"children": [{
		"hangYeFenLeiDaiMa": "A01",
		"hangYeFenLeiName": "农业",
    "pid": 'A',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "A02",
		"hangYeFenLeiName": "林业",
    "pid": 'A',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "A03",
		"hangYeFenLeiName": "畜牧业",
    "pid": 'A',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "A04",
		"hangYeFenLeiName": "渔业",
    "pid": 'A',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "A05",
		"hangYeFenLeiName": "农、林、牧、渔服务业",
    "pid": 'A',
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "K",
	"hangYeFenLeiName": "房地产业",
	"children": [{
		"hangYeFenLeiDaiMa": "K70",
		"hangYeFenLeiName": "房地产业",
    "pid": 'K',
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "G",
	"hangYeFenLeiName": "交通运输、仓储和邮政业",
	"children": [{
		"hangYeFenLeiDaiMa": "G53",
		"hangYeFenLeiName": "铁路运输业",
    "pid": 'G',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "G54",
		"hangYeFenLeiName": "道路运输业",
    "pid": 'G',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "G55",
		"hangYeFenLeiName": "水上运输业",
    "pid": 'G',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "G56",
		"hangYeFenLeiName": "航空运输业",
    "pid": 'G',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "G57",
		"hangYeFenLeiName": "管道运输业",
    "pid": 'G',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "G58",
		"hangYeFenLeiName": "装卸搬运和运输代理业",
    "pid": 'G',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "G59",
		"hangYeFenLeiName": "仓储业",
    "pid": 'G',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "G60",
		"hangYeFenLeiName": "邮政业",
    "pid": 'G',
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "T",
	"hangYeFenLeiName": "国际组织",
	"children": [{
		"hangYeFenLeiDaiMa": "T96",
		"hangYeFenLeiName": "国际组织",
    "pid": 'T',
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "D",
	"hangYeFenLeiName": "电力、热力、燃气及水生产和供应业",
	"children": [{
		"hangYeFenLeiDaiMa": "D44",
		"hangYeFenLeiName": "电力、热力生产和供应业",
    "pid": 'D',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "D45",
		"hangYeFenLeiName": "燃气生产和供应业",
    "pid": 'D',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "D46",
		"hangYeFenLeiName": "水的生产和供应业",
    "pid": 'D',
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "P",
	"hangYeFenLeiName": "教育",
	"children": [{
		"hangYeFenLeiDaiMa": "P82",
		"hangYeFenLeiName": "教育",
    "pid": 'P',
		"children": []
	}]
}, {
	"hangYeFenLeiDaiMa": "Q",
	"hangYeFenLeiName": "卫生和社会工作",
	"children": [{
		"hangYeFenLeiDaiMa": "Q83",
		"hangYeFenLeiName": "卫生",
    "pid": 'Q',
		"children": []
	}, {
		"hangYeFenLeiDaiMa": "Q84",
		"hangYeFenLeiName": "社会工作",
    "pid": 'Q',
		"children": []
	}]
}]
